// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "DEVICE_LOGIN_NAME";

const char SSID[]               = "SSID";    // Network SSID (name)
const char PASS[]               = "PASS";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "DEVICE_KEY";    // Secret device password

// ----------------------------
// Add a switch for each device
// ----------------------------
void onPowerPCChange();

CloudSwitch powerPC;

void initProperties(){
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(powerPC, READWRITE, ON_CHANGE, onPowerPCChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

WiFiUDP udp;
const int WOL_PORT = 9;

