/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnectionRouteImport } from './routes/connection'
import { Route as IndexRouteImport } from './routes/index'

const ConnectionRoute = ConnectionRouteImport.update({
  id: '/connection',
  path: '/connection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connection': typeof ConnectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connection': typeof ConnectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connection': typeof ConnectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/connection'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connection'
  id: '__root__' | '/' | '/connection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionRoute: typeof ConnectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/connection': {
      id: '/connection'
      path: '/connection'
      fullPath: '/connection'
      preLoaderRoute: typeof ConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionRoute: ConnectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
